repos:
    -   repo: https://github.com/psf/black
        rev: 22.3.0
        hooks:
        -   id: black
    -   repo: https://github.com/timothycrosley/isort
        rev: 5.12.0
        hooks:
        -   id: isort
            args: ["--profile", "black"]
    -   repo: https://github.com/pycqa/flake8
        rev: 3.9.2
        hooks:
        -   id: flake8
    -   repo: https://github.com/pre-commit/mirrors-clang-format
        rev: 'v15.0.7'
        hooks:
        -   id: clang-format
            exclude_types: [c#, java, javascript, json, proto]
            exclude: >
              (?x)^(
                build |
                renderers/agg/ |
                flatgeobuf/ |
                opengl/ |
                third-party/ |
                maplexer.c |
                mapparser.c |
                mapparser.h |
                dejavu-sans-condensed.h |
                uthash.h
              )
