#!/bin/sh

VALGRIND=$1
RUN_TEST=test/run_test

$RUN_TEST $VALGRIND 4001 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf"
  xmlns:xlink="http://www.w3.org/1999/xlink">
	<wfs:Insert handle="ins-1">
      <sf:AggregateGeoFeature gml:id="cite.gmlsf0-f12">
        <gml:description>
        Maecenas fermentum, massa ac ornare tristique, sem est tempus justo, 
        sed euismod urna ante ut pede. Nam condimentum sapien ut quam.
        </gml:description>
        <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f12</gml:name>
        <gml:boundedBy>
          <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:lowerCorner>35.84 0.14</gml:lowerCorner>
            <gml:upperCorner>56.54 12.37</gml:upperCorner>
          </gml:Envelope>
        </gml:boundedBy>
        <sf:multiCurveProperty>
          <gml:MultiCurve srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:description>Aenean convallis pede non quam</gml:description>
            <gml:curveMember>
              <gml:LineString>
                <gml:posList>35.840973 0.14967346 44.11891 3.6755037 48.36785 9.001808 39.459682 9.716776</gml:posList>
              </gml:LineString>
            </gml:curveMember>
            <gml:curveMember>
              <gml:LineString>
                <gml:posList>51.174034 12.365124 55.288635 7.583888 56.534782 4.1457024</gml:posList>
              </gml:LineString>
            </gml:curveMember>
          </gml:MultiCurve>
        </sf:multiCurveProperty>
        <sf:doubleProperty>2.4510E4</sf:doubleProperty>
        <sf:intRangeProperty>99</sf:intRangeProperty>
        <sf:strProperty>Fusce turpis est, ultricies sed, luctus quis, blandit ac, massa</sf:strProperty>
        <sf:featureCode>AT030</sf:featureCode>
      </sf:AggregateGeoFeature>
    </wfs:Insert>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4002 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
	<wfs:Insert handle="insert-1" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
      <sf:PrimitiveGeoFeature gml:id="cite.gmlsf0-f04">
        <gml:description>
        Cras vehicula, ligula vel tincidunt imperdiet, ligula arcu convallis 
        dolor, sed convallis diam dolor vitae urna. Mauris quis risus at urna 
        interdum porttitor.
        </gml:description>
        <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f04</gml:name>
        <sf:surfaceProperty>
          <gml:Polygon>
            <gml:exterior>
              <gml:LinearRing>
                <gml:posList>52.234646 11.661083 48.222664 21.77039 53.234585 29.490486 58.224674 22.1420336 52.234646 11.661083</gml:posList>
              </gml:LinearRing>
            </gml:exterior>
            <gml:interior>
              <gml:LinearRing>
                <gml:posList>54.78090 20.804808 53.01941 22.17321 54.02851 23.28652 54.78090 20.804808</gml:posList>
              </gml:LinearRing>
            </gml:interior>
          </gml:Polygon>
        </sf:surfaceProperty>
        <sf:pointProperty>
          <gml:Point><gml:pos>53.11942 22.27320</gml:pos></gml:Point>
        </sf:pointProperty>
        <sf:intProperty>10257</sf:intProperty>
        <sf:uriProperty>ftp://ftp.irisa.fr/pub/gnu/</sf:uriProperty>
        <sf:measurand>219.1</sf:measurand>
        <sf:dateProperty>2006-02-09</sf:dateProperty>
        <sf:decimalProperty>120.2</sf:decimalProperty>
      </sf:PrimitiveGeoFeature>
    </wfs:Insert>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4003 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
	<wfs:Insert handle="ins-1">
      <sf:PrimitiveGeoFeature gml:id="cite.gmlsf0-f10">
        <sf:pointProperty>
          <gml:Point srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:pos>70.823555 -7.735101</gml:pos>
          </gml:Point>
        </sf:pointProperty>
        <sf:intProperty>987654321</sf:intProperty>
        <sf:measurand>270.6</sf:measurand>
        <sf:decimalProperty>2.71</sf:decimalProperty>
      </sf:PrimitiveGeoFeature>
    </wfs:Insert>
    
    <wfs:Update handle="upd-1" typeName="sf:PrimitiveGeoFeature">
      <wfs:Property>
        <wfs:Name>sf:pointProperty</wfs:Name>
        <wfs:Value>
          <gml:Point>
            <gml:pos>5311942 2227320 12.34</gml:pos>
          </gml:Point>
        </wfs:Value>
      </wfs:Property>
      <ogc:Filter>
        <ogc:PropertyIsEqualTo>
          <ogc:PropertyName>sf:intProperty</ogc:PropertyName>
          <ogc:Literal>987654321</ogc:Literal>
        </ogc:PropertyIsEqualTo>
      </ogc:Filter>
    </wfs:Update>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4004 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf"
  xmlns:xlink="http://www.w3.org/1999/xlink">
	<wfs:Insert handle="ins-1">
      <sf:PrimitiveGeoFeature gml:id="cite.gmlsf0-f13">
        <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f13</gml:name>
        <sf:pointProperty>
          <gml:Point srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:pos>62.12409 12.19653797</gml:pos>
          </gml:Point>
        </sf:pointProperty>
        <sf:intProperty>235711</sf:intProperty>
        <sf:measurand>6.12</sf:measurand>
        <sf:decimalProperty>10.16</sf:decimalProperty>
      </sf:PrimitiveGeoFeature>
    </wfs:Insert>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4005 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
	<wfs:Insert handle="ins-1">
      <sf:PrimitiveGeoFeature gml:id="cite.gmlsf0-f07">
        <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f07</gml:name>
        <sf:surfaceProperty>
          <gml:Polygon srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:exterior>
              <gml:LinearRing>
                <gml:posList>57.28665 21.368711 56.118668 22.280576 56.407759 23.579485 57.39861 22.919643 58.49861 22.756339 57.79861 21.919643 57.28665 21.368711</gml:posList>
              </gml:LinearRing>
            </gml:exterior>
            <gml:interior>
              <gml:LinearRing>
                <gml:posList>57.06574 22.079622 57.06574 22.660713 57.34563 22.950624 57.06574 22.079622</gml:posList>
              </gml:LinearRing>
            </gml:interior>				
	      </gml:Polygon>
        </sf:surfaceProperty>
        <sf:intProperty>1234567890</sf:intProperty>
        <sf:measurand>285.1</sf:measurand>
        <sf:decimalProperty>22.71</sf:decimalProperty>
      </sf:PrimitiveGeoFeature>
    </wfs:Insert>
    
    <wfs:Delete handle="del-1" typeName="sf:PrimitiveGeoFeature">
      <ogc:Filter>
        <ogc:PropertyIsGreaterThanOrEqualTo>
          <ogc:PropertyName>sf:intProperty</ogc:PropertyName>
          <ogc:Literal>1234567890</ogc:Literal>
        </ogc:PropertyIsGreaterThanOrEqualTo>
      </ogc:Filter>
    </wfs:Delete>
    
    <wfs:Update handle="upd-1" typeName="sf:PrimitiveGeoFeature">
      <wfs:Property>
        <wfs:Name>sf:measurand</wfs:Name>
        <wfs:Value>286.0</wfs:Value>
      </wfs:Property>
      <ogc:Filter>
        <ogc:PropertyIsEqualTo matchCase="false">
          <ogc:PropertyName>gml:name</ogc:PropertyName>
          <ogc:Literal>cite.gmlsf0-f07</ogc:Literal>
        </ogc:PropertyIsEqualTo>
      </ogc:Filter>
    </wfs:Update>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4006 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf"
  xmlns:xlink="http://www.w3.org/1999/xlink">
	<wfs:Insert handle="ins-1">
      <sf:PrimitiveGeoFeature gml:id="cite.gmlsf0-f16">
        <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f16</gml:name>
        <sf:curveProperty>
          <gml:LineString srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:posList>48.76926 27.590446 46.54372 24.856320 42.89878 20.067233 42.414574 15.148127</gml:posList>
          </gml:LineString>
        </sf:curveProperty>
        <sf:intProperty>76512</sf:intProperty>
        <sf:measurand>8000</sf:measurand>
        <sf:dateTimeProperty>2006-07-30T08:34:12+01:00</sf:dateTimeProperty>
        <sf:decimalProperty>75.12</sf:decimalProperty>
      </sf:PrimitiveGeoFeature>
      <sf:PrimitiveGeoFeature gml:id="cite.gmlsf0-f17">
        <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f17</gml:name>
        <sf:curveProperty>
          <gml:LineString srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:posList>46.76926 25.590446 45.54372 22.856320 41.89878 18.067233 41.414574 13.148127 39.414574 9.148127</gml:posList>
          </gml:LineString>
        </sf:curveProperty>
        <sf:intProperty>111222</sf:intProperty>
        <sf:measurand>450</sf:measurand>
        <sf:dateTimeProperty>2005-11-22T11:51:43+02:00</sf:dateTimeProperty>
        <sf:decimalProperty>15.12</sf:decimalProperty>
      </sf:PrimitiveGeoFeature>
      <sf:EntitéGénérique gml:id="cite.gmlsf0-f18">
        <gml:description>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</gml:description>
        <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f18</gml:name>
        <sf:attribut.Géométrie>
          <gml:LineString srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:posList>52.68416 0.826830 50.19039 3.537679 53.00112 5.850914 54.53406 13.099472 54.400627 18.411608</gml:posList>
          </gml:LineString>
        </sf:attribut.Géométrie>
        <sf:boolProperty>true</sf:boolProperty>
        <sf:str4Property>wxÿz</sf:str4Property>
        <sf:featureRef>cite.gmlsf0-f16</sf:featureRef>
      </sf:EntitéGénérique>
    </wfs:Insert>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4007 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc" 
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
    <wfs:Delete handle="del-1" typeName="sf:PrimitiveGeoFeature">
      <ogc:Filter>
        <ogc:GmlObjectId gml:id="{$fid1}" />
        <ogc:GmlObjectId gml:id="{$fid2}" />
      </ogc:Filter>
    </wfs:Delete>
    <wfs:Delete handle="del-2" typeName="sf:EntitéGénérique">
      <ogc:Filter>
        <ogc:GmlObjectId gml:id="{$fid3}" />
      </ogc:Filter>
    </wfs:Delete>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4008 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
	<wfs:Insert handle="ins-1">
      <sf:EntitéGénérique gml:id="cite.gmlsf0-f08">
        <gml:description>
        Maecenas nisi. Cum sociis natoque penatibus et magnis dis parturient montes, 
        nascetur ridiculus mŭs. Fuscè condimentum cursus ipsum. Proin at nisl quis 
        massa accumsan aliquam. Aliquam erat volutpat. Morbi volutpat tempor mi. 
        Ut eget libero in lacus aliquam dignissim. Vivamus aliquam odio ut libero. 
        Ćurabitur bibendum felis vitae tellus
        </gml:description>
        <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f08</gml:name>
        <sf:attribut.Géométrie>
          <gml:Polygon gml:id="cite.gmlsf0-g08" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:exterior>
              <gml:LinearRing>
                <gml:posList>65.52752 20.989298 52.09453 19.720014 49.102436 14.609264 60.92411 11.851856 60.04618 16.19630 65.52752 20.989298</gml:posList>
              </gml:LinearRing>
            </gml:exterior>
          </gml:Polygon>
        </sf:attribut.Géométrie>
        <sf:boolProperty>false</sf:boolProperty>
        <sf:str4Property>tuv7</sf:str4Property>
      </sf:EntitéGénérique>
    </wfs:Insert>
    
    <wfs:Update handle="upd-1" typeName="sf:EntitéGénérique">
      <wfs:Property>
        <wfs:Name>sf:attribut.Géométrie</wfs:Name>
        <wfs:Value>
          <gml:MultiSurface gml:id="cite.gmlsf0-g09" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:surfaceMember>
              <gml:Polygon>
                <gml:exterior>
                  <gml:LinearRing>
                    <gml:posList>65.52752 20.989298 52.09453 19.720014 49.102436 14.609264 60.92411 11.851856 60.04618 16.19630 65.52752 20.989298</gml:posList>
                  </gml:LinearRing>
                </gml:exterior>
              </gml:Polygon>
            </gml:surfaceMember>
            <gml:surfaceMember>
              <gml:Polygon>
                <gml:exterior>
                  <gml:LinearRing>
                    <gml:posList>48.41841 12.878309 42.19452 14.521905 39.102436 10.204653 45.82511 10.051956 48.41841 12.878309</gml:posList>
                  </gml:LinearRing>
                </gml:exterior>
              </gml:Polygon>
            </gml:surfaceMember>
          </gml:MultiSurface>
        </wfs:Value>
      </wfs:Property>
      <ogc:Filter>
        <ogc:PropertyIsEqualTo>
          <ogc:PropertyName>sf:str4Property</ogc:PropertyName>
          <ogc:Literal>tuv7</ogc:Literal>
        </ogc:PropertyIsEqualTo>
      </ogc:Filter>
    </wfs:Update>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4009 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
    <wfs:Delete handle="del-1" typeName="sf:PrimitiveGeoFeature" />
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4010 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
    
    <wfs:Update handle="upd-1" typeName="sf:PrimitiveGeoFeature">
      <wfs:Property>
        <wfs:Name>sf:surfaceProperty</wfs:Name>
        <wfs:Value>
          <gml:MultiCurve srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:curveMember>
              <gml:LineString>
                <gml:posList>35.840973 0.14967346 44.11891 3.6755037 48.36785 9.001808 39.459682 9.716776</gml:posList>
              </gml:LineString>
            </gml:curveMember>
            <gml:curveMember>
              <gml:LineString>
                <gml:posList>51.174034 12.365124 55.288635 7.583888 56.534782 4.1457024</gml:posList>
              </gml:LineString>
            </gml:curveMember>
          </gml:MultiCurve>
        </wfs:Value>
      </wfs:Property>
      <ogc:Filter>
        <ogc:GmlObjectId gml:id="{$fid}" />
      </ogc:Filter>
    </wfs:Update>
    <wfs:Update handle="upd-2" typeName="sf:PrimitiveGeoFeature">
      <wfs:Property>
        <wfs:Name>sf:dateProperty</wfs:Name>
        <wfs:Value>2006-05-07T12:51:00Z</wfs:Value>
      </wfs:Property>
      <ogc:Filter>
        <ogc:GmlObjectId gml:id="{$fid}" />
      </ogc:Filter>
    </wfs:Update>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4011 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
	<wfs:Insert handle="ins-1">
      <sf:AggregateGeoFeature gml:id="cite.gmlsf0-f26">
        <gml:description>Curabitur auctor ipsum condimentum tortor lacinia auctor.</gml:description>
        <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f26</gml:name>
        <sf:multiSurfaceProperty>
          <gml:MultiSurface gml:id="cite.gmlsf0-g05" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:surfaceMember>
              <gml:Polygon>
                <gml:exterior>
                  <gml:LinearRing>
                  <gml:posList>41.929283 4.3031006 62.029465 16.708838 37.929283 10.3022007 41.929283 4.3031006</gml:posList>
                  </gml:LinearRing>
                </gml:exterior>
              </gml:Polygon>
            </gml:surfaceMember>
            <gml:surfaceMember>
              <gml:Polygon>
                <gml:exterior>
                  <gml:LinearRing>
                  <gml:posList>54.84978 -5.3175583 60.65348 -1.426458 50.93067 0.5084481 47.445404 -2.7623253 48.545404 -4.9623253 54.84978 -5.3175583</gml:posList>
                  </gml:LinearRing>
                </gml:exterior>
                <gml:interior>
                  <gml:LinearRing>
                  <gml:posList>51.913918 -4.0407763 52.09126 -3.26674 50.08543 -3.45352 51.913918 -4.0407763</gml:posList>
                  </gml:LinearRing>
                </gml:interior>
                <gml:interior>
                  <gml:LinearRing>
                  <gml:posList>55.922027 -2.1316851 58.18017 -1.46574 52.17441 -1.14361 55.922027 -2.1316851</gml:posList>
                  </gml:LinearRing>
                </gml:interior>
              </gml:Polygon>
            </gml:surfaceMember>
          </gml:MultiSurface>
        </sf:multiSurfaceProperty>
        <sf:doubleProperty>1267.09343</sf:doubleProperty>
        <sf:strProperty>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</sf:strProperty>
        <sf:featureCode>EA050</sf:featureCode>
      </sf:AggregateGeoFeature>
    </wfs:Insert>
    
    <wfs:Update handle="upd-1" typeName="sf:AggregateGeoFeature">
      <wfs:Property>
        <wfs:Name>gml:name</wfs:Name>
        <wfs:Value>cite.gmlsf0-f26bis</wfs:Value>
      </wfs:Property>
      <ogc:Filter>
        <ogc:PropertyIsEqualTo matchCase="false">
          <ogc:PropertyName>sf:featureCode</ogc:PropertyName>
          <ogc:Literal>ea050</ogc:Literal>
        </ogc:PropertyIsEqualTo>
      </ogc:Filter>
    </wfs:Update>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4012 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
    
    <wfs:Update handle="upd-1" typeName="sf:PrimitiveGeoFeature">
      <wfs:Property>
        <wfs:Name>sf:measurand</wfs:Name>
        <wfs:Value>6.24</wfs:Value>
      </wfs:Property>
      <wfs:Property>
        <wfs:Name>gml:name</wfs:Name>
        <wfs:Value>cite.gmlsf0-f13bis</wfs:Value>
      </wfs:Property>
      <ogc:Filter>
        <ogc:GmlObjectId gml:id="{$fid}" />
      </ogc:Filter>
    </wfs:Update>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4013 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
    
    <wfs:Update handle="upd-1" typeName="sf:PrimitiveGeoFeature">
      <wfs:Property>
        <wfs:Name>gml:name</wfs:Name>
      </wfs:Property>
      <ogc:Filter>
        <ogc:GmlObjectId gml:id="{$fid}" />
      </ogc:Filter>
    </wfs:Update>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4014 '
<wfs:Transaction version="1.1.0" service="WFS"
  xmlns:wfs="http://www.opengis.net/wfs">
  <wfs:Native vendorId="cite.wfs.foo" safeToIgnore="false" />
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4015 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
	<wfs:Insert handle="insert-tc2.2" srsName="urn:x-ogc:def:crs:FOO:6.11.2:9999">
      <sf:PrimitiveGeoFeature gml:id="cite.gmlsf0-f94">
        <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f94</gml:name>
        <sf:pointProperty>
          <gml:Point>
            <gml:pos>5311942 2227320</gml:pos>
          </gml:Point>
        </sf:pointProperty>
        <sf:intProperty>10257</sf:intProperty>
        <sf:uriProperty>ftp://ftp.irisa.fr/pub/gnu/</sf:uriProperty>
        <sf:measurand>219.1</sf:measurand>
        <sf:dateProperty>2006-02-09</sf:dateProperty>
        <sf:decimalProperty>120.2</sf:decimalProperty>
      </sf:PrimitiveGeoFeature>
    </wfs:Insert>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4016 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf"
  xmlns:xlink="http://www.w3.org/1999/xlink">
	<wfs:Insert handle="ins-1">
      <sf:PrimitiveGeoFeature gml:id="cite.gmlsf0-f13">
        <gml:description>
        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere 
        cubilia Curae; maecenas elu dictum.
        </gml:description>
        <sf:surfaceProperty>
          <gml:Polygon srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:description>Aenean convallis pede non quam</gml:description>
            <gml:exterior>
              <gml:LinearRing>
                <gml:posList>65.86066 -6.802099 60.43201 -3.398107 49.62552 -4.018872 52.680374 -6.822956 65.86066 -6.802099</gml:posList>
              </gml:LinearRing>
            </gml:exterior>
          </gml:Polygon>
        </sf:surfaceProperty>
        <sf:intProperty>111222</sf:intProperty>
        <sf:uriProperty>ldap://ldap.ufoo.edu/o=University%20of%20Foo,c=NN</sf:uriProperty>
        <sf:measurand>3731</sf:measurand>
        <sf:dateProperty>2006-05-07</sf:dateProperty>
        <sf:decimalProperty>0.98</sf:decimalProperty>
      </sf:PrimitiveGeoFeature>
    </wfs:Insert>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4017 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
	<wfs:Insert handle="ins-1">
      <sf:PrimitiveGeoFeature gml:id="cite.gmlsf0-f14">
        <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f14</gml:name>
        <sf:pointProperty>
          <gml:Point srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:pos>69.21915 19.314623</gml:pos>
          </gml:Point>
        </sf:pointProperty>
        <sf:intProperty>71921</sf:intProperty>
        <sf:measurand>94.6</sf:measurand>
        <sf:decimalProperty>9.02</sf:decimalProperty>
      </sf:PrimitiveGeoFeature>
    </wfs:Insert>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4018 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
	<wfs:Insert handle="insert-1">
      <sf:PrimitiveGeoFeature gml:id="cite.gmlsf0-f01">
        <gml:description>
        Fusce tellus ante, tempus nonummy, ornare sed, accumsan nec, leo. 
        Vivamus pulvinar molestie nisl.
        </gml:description>
        <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f01</gml:name>
        <sf:curveProperty>
          <gml:LineString gml:id="cite.gmlsf0-g01" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:posList>47.608284 19.034142 51.286873 16.7836 49.849854 15.764992</gml:posList>
          </gml:LineString>
        </sf:curveProperty>
        <sf:intProperty>1025</sf:intProperty>
        <sf:measurand>7.405E2</sf:measurand>
        <sf:dateTimeProperty>2006-06-23T12:43:12+01:00</sf:dateTimeProperty>
        <sf:decimalProperty>90.62</sf:decimalProperty>
      </sf:PrimitiveGeoFeature>
    </wfs:Insert>

    <wfs:Insert handle="insert-2">
      <sf:AggregateGeoFeature gml:id="cite.gmlsf0-f02">
        <gml:description>
        Duis nulla nisi, molestie vel, rhoncus a, ullamcorper eu, justo. Sed bibendum. 
        Ut sem. Mauris nec nunc a eros aliquet pharetra. Mauris nonummy, pede et 
        tincidunt ultrices, mauris lectus fermentum massa, in ullamcorper lectus 
        felis vitae metus. Quisqué viverra.
        </gml:description>
        <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f02</gml:name>
        <gml:boundedBy>
          <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:lowerCorner>36.1 8.0</gml:lowerCorner>
            <gml:upperCorner>52.0 21.1</gml:upperCorner>
          </gml:Envelope>
        </gml:boundedBy>
        <sf:multiPointProperty>
          <gml:MultiPoint srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:pointMember>
              <gml:Point><gml:pos>49.325176 21.036873</gml:pos></gml:Point>
            </gml:pointMember>
            <gml:pointMember>
              <gml:Point><gml:pos>36.142586 13.56189</gml:pos></gml:Point>
            </gml:pointMember>
            <gml:pointMember>
              <gml:Point><gml:pos>51.920937 8.014193</gml:pos></gml:Point>
            </gml:pointMember>
          </gml:MultiPoint>
        </sf:multiPointProperty>
        <sf:doubleProperty>2012.78</sf:doubleProperty>
        <sf:intRangeProperty>43</sf:intRangeProperty>
        <sf:strProperty>
        Donec ligulä pede, sodales iń, vehicula eu, sodales et, lêo.
        </sf:strProperty>
        <sf:featureCode>AK121</sf:featureCode>
      </sf:AggregateGeoFeature>
      
      <sf:EntitéGénérique gml:id="cite.gmlsf0-f03">
        <gml:description>
        Suspendisse in odio sit amet lorem dictum semper. Integer ultrices purus 
        vel orci. Donec felis massa, suscipit a, lacinia nec, rhoncus vulputate, 
        tellus.
        </gml:description>
        <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f03</gml:name>
        <sf:attribut.Géométrie>
          <gml:LineString gml:id="cite.gmlsf0-g04" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:description>Curabitur ut enim at metus vehicula</gml:description>
            <gml:posList>47.35948 0.06282902 45.62291 -0.6651201 44.34261 -2.341187 45.08817 -2.696537 45.953514 -3.793995 47.21312 -2.773082 48.644974 -3.131115</gml:posList>
          </gml:LineString>
        </sf:attribut.Géométrie>
        <sf:boolProperty>true</sf:boolProperty>
        <sf:str4Property>ghij</sf:str4Property>
        <sf:featureRef>cite.gmlsf0-f01</sf:featureRef>
      </sf:EntitéGénérique>
    </wfs:Insert>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4019 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
    
    <wfs:Update handle="upd-1" typeName="sf:AggregateGeoFeature">
      <wfs:Property>
        <wfs:Name>sf:doubleProperty</wfs:Name>
      </wfs:Property>
      <ogc:Filter>
        <ogc:GmlObjectId gml:id="{$fid}" />
      </ogc:Filter>
    </wfs:Update>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 4020 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
	<wfs:Insert handle="insert-1">
      <sf:PrimitiveGeoFeature gml:id="cite.gmlsf0-f05">
        <sf:pointProperty>
          <gml:Point srsName="urn:x-ogc:def:crs:FOO:2006.10:9999">
            <gml:pos>5311942 2227320</gml:pos>
          </gml:Point>
        </sf:pointProperty>
        <sf:intProperty>9999</sf:intProperty>
        <sf:measurand>283.5</sf:measurand>
        <sf:decimalProperty>12.18</sf:decimalProperty>
      </sf:PrimitiveGeoFeature>
    </wfs:Insert>
    <wfs:Insert handle="insert-2">
    <sf:EntitéGénérique gml:id="cite.gmlsf0-f06">
      <gml:description>Curabitur auctor ipsum condimentum tortor lacinia auctor.</gml:description>
      <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f06</gml:name>
      <sf:attribut.Géométrie>
        <gml:MultiCurve gml:id="cite.gmlsf0-g04" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:name>Sed magna</gml:name>
          <gml:curveMember>
            <gml:LineString>
              <gml:posList>56.913918 4.5407763 56.09126 9.26674 53.98543 12.45352 52.68249 13.9302635</gml:posList>
            </gml:LineString>
          </gml:curveMember>
          <gml:curveMember>
            <gml:LineString>
              <gml:posList>35.285793 9.72645 36.75665 1.05434 38.630505 -5.7180705</gml:posList>
            </gml:LineString>
          </gml:curveMember>
        </gml:MultiCurve>
      </sf:attribut.Géométrie>
      <sf:boolProperty>true</sf:boolProperty>
      <sf:str4Property>ijk8</sf:str4Property>
    </sf:EntitéGénérique>
    </wfs:Insert>
</wfs:Transaction>
'

