#!/bin/sh

VALGRIND=$1
RUN_TEST=test/run_test

$RUN_TEST $VALGRIND 5001 '
<wfs:LockFeature service="WFS" version="1.1.0" 
  handle="LockFeature-tc1"
  expiry="5"
  lockAction="ALL"
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
  
  <wfs:Lock handle="lock-1" typeName="sf:PrimitiveGeoFeature" />
</wfs:LockFeature>
'

$RUN_TEST $VALGRIND 5002 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
	<wfs:Insert handle="insert-1">
      <sf:PrimitiveGeoFeature gml:id="cite.gmlsf0-f501">
        <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f501</gml:name>
        <sf:curveProperty>
          <gml:LineString srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:posList>48.608284 20.034142 50.286873 15.7836 50.849854 16.764992</gml:posList>
          </gml:LineString>
        </sf:curveProperty>
        <sf:intProperty>1025</sf:intProperty>
        <sf:measurand>63.94</sf:measurand>
        <sf:dateTimeProperty>2006-08-23T13:45:12Z</sf:dateTimeProperty>
        <sf:decimalProperty>92.51</sf:decimalProperty>
      </sf:PrimitiveGeoFeature>
    </wfs:Insert>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 5003 '
<wfs:LockFeature service="WFS" version="1.1.0" 
  handle="LockFeature-tc3"
  expiry="5"
  lockAction="ALL"
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf"
  xmlns:ogc="http://www.opengis.net/ogc">
  
  <wfs:Lock handle="lock-1" typeName="sf:EntitéGénérique">
    <ogc:Filter>
      <ogc:BBOX>
        <ogc:PropertyName xmlns:sf="http://cite.opengeospatial.org/gmlsf">sf:attribut.Géométrie</ogc:PropertyName>
        <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:lowerCorner>34.5 -10.0</gml:lowerCorner>
          <gml:upperCorner>72.0 32.0</gml:upperCorner>
        </gml:Envelope>
      </ogc:BBOX>
    </ogc:Filter>
  </wfs:Lock>
</wfs:LockFeature>
'

$RUN_TEST $VALGRIND 5004 '
<wfs:Transaction service="WFS" version="1.1.0" 
  releaseAction="ALL"
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc" 
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <wfs:LockId><xsl:value-of select="$LockId"/></wfs:LockId>
    <wfs:Delete handle="upd-1" typeName="sf:PrimitiveGeoFeature">
        <ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>gml:name</ogc:PropertyName>
				<ogc:Literal>cite.gmlsf0-f501</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
    </wfs:Delete>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 5005 '
<wfs:Transaction service="WFS" version="1.1.0" 
  releaseAction="SOME"
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc"  
  xmlns:gml="http://www.opengis.net/gml"
  xmlns:sf="http://cite.opengeospatial.org/gmlsf"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <wfs:LockId><xsl:value-of select="$LockId"/></wfs:LockId>
    <wfs:Update handle="upd-1" typeName="sf:EntitéGénérique">
      <wfs:Property>
        <wfs:Name>sf:boolProperty</wfs:Name>
        <wfs:Value>true</wfs:Value>
      </wfs:Property>
      <ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>gml:name</ogc:PropertyName>
				<ogc:Literal>cite.gmlsf0-f502</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
    </wfs:Update>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 5006 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc"  
  xmlns:gml="http://www.opengis.net/gml"
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
    <wfs:Delete handle="del-1" typeName="sf:EntitéGénérique">
      <ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>gml:name</ogc:PropertyName>
				<ogc:Literal>cite.gmlsf0-f502</ogc:Literal>
			</ogc:PropertyIsEqualTo>
	  </ogc:Filter>
    </wfs:Delete>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 5007 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc"  
  xmlns:gml="http://www.opengis.net/gml"
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
    <wfs:Delete handle="del-1" typeName="sf:EntitéGénérique">
      <ogc:Filter>
        <ogc:BBOX>
          <ogc:PropertyName xmlns:sf="http://cite.opengeospatial.org/gmlsf">sf:attribut.Géométrie</ogc:PropertyName>
          <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:lowerCorner>34.5 -10.0</gml:lowerCorner>
            <gml:upperCorner>72.0 32.0</gml:upperCorner>
          </gml:Envelope>
        </ogc:BBOX>
      </ogc:Filter>
    </wfs:Delete>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 5008 '
<wfs:Transaction service="WFS" version="1.1.0" 
  releaseAction="ALL"
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc" 
  xmlns:gml="http://www.opengis.net/gml">
    <wfs:LockId>a986ef12-75b8-477a-841f-3c496525ddf5</wfs:LockId>
    <wfs:Delete handle="del-1" typeName="sf:PrimitiveGeoFeature">
      <ogc:Filter>
        <ogc:BBOX>
          <ogc:PropertyName xmlns:sf="http://cite.opengeospatial.org/gmlsf">sf:pointProperty</ogc:PropertyName>
          <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11:4326">
            <gml:lowerCorner>39.2 -1.0</gml:lowerCorner>
            <gml:upperCorner>40.0 4.0</gml:upperCorner>
          </gml:Envelope>
        </ogc:BBOX>
      </ogc:Filter>
    </wfs:Delete>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 5009 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:ogc="http://www.opengis.net/ogc" 
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
    <wfs:Delete handle="del-1" typeName="sf:PrimitiveGeoFeature">
      <ogc:Filter>
        <ogc:GmlObjectId gml:id="{$fid}" />
      </ogc:Filter>
    </wfs:Delete>
</wfs:Transaction>
'

$RUN_TEST $VALGRIND 5010 '
<wfs:Transaction service="WFS" version="1.1.0" 
  xmlns:wfs="http://www.opengis.net/wfs" 
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:sf="http://cite.opengeospatial.org/gmlsf">
	<wfs:Insert handle="insert-1">
      <sf:EntitéGénérique gml:id="cite.gmlsf0-f502">
        <gml:name codeSpace="http://cite.opengeospatial.org/gmlsf">cite.gmlsf0-f502</gml:name>
        <sf:attribut.Géométrie>
          <gml:Point srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:pos>68.723555 -5.635101</gml:pos>
          </gml:Point>
        </sf:attribut.Géométrie>
        <sf:boolProperty>false</sf:boolProperty>
        <sf:str4Property>#!/_</sf:str4Property>
      </sf:EntitéGénérique>
    </wfs:Insert>
</wfs:Transaction>
'

