#!/bin/sh

VALGRIND=$1
RUN_TEST=test/run_test

$RUN_TEST $VALGRIND 3001 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>sf:intProperty</ogc:PropertyName>
				<ogc:Literal>300</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3002 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    xmlns:ogc="http://www.opengis.net/ogc" 
    typeName="sf:PrimitiveGeoFeature"
    srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
    <ogc:SortBy>
      <ogc:SortProperty>
        <ogc:PropertyName>sf:intProperty</ogc:PropertyName>
        <ogc:SortOrder>ASC</ogc:SortOrder>
      </ogc:SortProperty>
    </ogc:SortBy>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3003 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsLessThan>
				<ogc:PropertyName>sf:dateProperty</ogc:PropertyName>
				<ogc:Literal>2006-10-23Z</ogc:Literal>
			</ogc:PropertyIsLessThan>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3004 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsBetween>
				<ogc:PropertyName>sf:dateProperty</ogc:PropertyName>
				<ogc:LowerBoundary><ogc:Literal>2006-09-01Z</ogc:Literal></ogc:LowerBoundary>
				<ogc:UpperBoundary><ogc:Literal>2006-11-01Z</ogc:Literal></ogc:UpperBoundary>
			</ogc:PropertyIsBetween>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3005 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsLike wildCard="*" singleChar="?" escapeChar="\">
				<ogc:PropertyName>sf:strProperty</ogc:PropertyName>
				<ogc:Literal>*Ma quande lingues coalesce*</ogc:Literal>
			</ogc:PropertyIsLike>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3006 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsGreaterThanOrEqualTo>
				<ogc:PropertyName>sf:dateProperty</ogc:PropertyName>
				<ogc:Literal>2999-10-22</ogc:Literal>
			</ogc:PropertyIsGreaterThanOrEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3007 '
<wfs:GetFeatureLOL xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeatureLOL>'

$RUN_TEST $VALGRIND 3008 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsLessThanOrEqualTo>
				<ogc:PropertyName>sf:doubleProperty</ogc:PropertyName>
				<ogc:Literal>-200.009</ogc:Literal>
			</ogc:PropertyIsLessThanOrEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3009 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3010 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    xmlns:ogc="http://www.opengis.net/ogc" 
    typeName="sf:AggregateGeoFeature"
    srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
    <ogc:SortBy>
      <ogc:SortProperty>
        <ogc:PropertyName>sf:featureCode</ogc:PropertyName>
        <ogc:SortOrder>DESC</ogc:SortOrder>
      </ogc:SortProperty>
    </ogc:SortBy>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3011 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>sf:strProperty</ogc:PropertyName>
				<ogc:Literal>Ma quande lingues coalesce, li grammatica del resultant.</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3012 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature">
		<ogc:Filter>
			<ogc:BBOX>
				<ogc:PropertyName>sf:pointProperty</ogc:PropertyName>
				<gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
					<gml:lowerCorner>0 0</gml:lowerCorner>
					<gml:upperCorner>0.01 0.01</gml:upperCorner>
				</gml:Envelope>
			</ogc:BBOX>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3013 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>sf:dateProperty</ogc:PropertyName>
				<ogc:Literal>2006-12-12Z</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3014 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    xmlns:ogc="http://www.opengis.net/ogc" 
    typeName="sf:PrimitiveGeoFeature"
    srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
    <ogc:SortBy>
      <ogc:SortProperty>
        <ogc:PropertyName>sf:dateProperty</ogc:PropertyName>
        <ogc:SortOrder>DESC</ogc:SortOrder>
      </ogc:SortProperty>
    </ogc:SortBy>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3015 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    xmlns:ogc="http://www.opengis.net/ogc" 
    typeName="sf:PrimitiveGeoFeature"
    srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
    <ogc:SortBy>
      <ogc:SortProperty>
        <ogc:PropertyName>sf:dateProperty</ogc:PropertyName>
        <ogc:SortOrder>ASC</ogc:SortOrder>
      </ogc:SortProperty>
    </ogc:SortBy>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3016 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsLessThanOrEqualTo>
				<ogc:PropertyName>sf:decimalProperty</ogc:PropertyName>
				<ogc:Literal>5.03</ogc:Literal>
			</ogc:PropertyIsLessThanOrEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3017 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="http://www.epsg.org/6.11.2/4326"/>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3018 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS" traverseXlinkDepth="*" traverseXlinkExpiry="3">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3019 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="2.0.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3020 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsGreaterThan>
				<ogc:PropertyName>sf:doubleProperty</ogc:PropertyName>
				<ogc:Literal>2012.78</ogc:Literal>
			</ogc:PropertyIsGreaterThan>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3021 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsGreaterThan>
				<ogc:PropertyName>sf:dateProperty</ogc:PropertyName>
				<ogc:Literal>2006-10-22Z</ogc:Literal>
			</ogc:PropertyIsGreaterThan>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3022 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsGreaterThanOrEqualTo>
				<ogc:PropertyName>sf:dateTimeProperty</ogc:PropertyName>
				<ogc:Literal>2006-06-28T07:06:00+02:00</ogc:Literal>
			</ogc:PropertyIsGreaterThanOrEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3023 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>*[position()=1]</ogc:PropertyName>
				<ogc:Literal>description-f001</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3024 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature">
    <wfs:PropertyName>sf:uriProperty</wfs:PropertyName>
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
      <ogc:PropertyIsNull>
        <ogc:PropertyName>sf:uriProperty</ogc:PropertyName>										
      </ogc:PropertyIsNull>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3025 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs"  xmlns:ogc="http://www.opengis.net/ogc" service="WFS" version="1.1.0">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName xmlns:gml="http://www.opengis.net/ASDF">gml:name</ogc:PropertyName>
				<ogc:Literal>name-f003</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3026 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" featureVersion="ALL" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3027 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature">
		<ogc:Filter>
			<ogc:BBOX>
				<ogc:PropertyName>sf:pointProperty</ogc:PropertyName>
				<gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
					<gml:lowerCorner>39.63245 1.90342</gml:lowerCorner>
					<gml:upperCorner>39.83245 2.10342</gml:upperCorner>
				</gml:Envelope>
			</ogc:BBOX>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3028 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>gml:name</ogc:PropertyName>
				<ogc:Literal>name-f002</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3029 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS" maxFeatures="2">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3030 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsGreaterThan>
				<ogc:PropertyName>sf:dateTimeProperty</ogc:PropertyName>
				<ogc:Literal>2006-06-28T19:08:00+02:00</ogc:Literal>
			</ogc:PropertyIsGreaterThan>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3031 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3032 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:EntitéGénérique" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3033 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs"  xmlns:ogc="http://www.opengis.net/ogc" service="WFS" version="1.1.0">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsGreaterThan>
				<ogc:PropertyName>sf:intProperty</ogc:PropertyName>
				<ogc:Literal>100</ogc:Literal>
			</ogc:PropertyIsGreaterThan>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'


# ARITHMETIC OPERATORS

$RUN_TEST $VALGRIND 3034 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>sf:intProperty</ogc:PropertyName>
				<ogc:Add>
					<ogc:PropertyName>sf:decimalProperty</ogc:PropertyName>
					<ogc:Literal>149.97</ogc:Literal>
				</ogc:Add>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3035 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsLessThanOrEqualTo>
				<ogc:PropertyName>sf:intProperty</ogc:PropertyName>
				<ogc:Mul>
					<ogc:PropertyName>sf:decimalProperty</ogc:PropertyName>
					<ogc:Literal>-1</ogc:Literal>
				</ogc:Mul>
			</ogc:PropertyIsLessThanOrEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3036 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>sf:doubleProperty</ogc:PropertyName>
				<ogc:Div>
					<ogc:PropertyName>sf:doubleProperty</ogc:PropertyName>
					<ogc:Literal>9999</ogc:Literal>
				</ogc:Div>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3037 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsGreaterThan>
				<ogc:PropertyName>sf:intProperty</ogc:PropertyName>
				<ogc:Add>
					<ogc:PropertyName>sf:decimalProperty</ogc:PropertyName>
					<ogc:Literal>1</ogc:Literal>
				</ogc:Add>
			</ogc:PropertyIsGreaterThan>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3038 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsGreaterThan>
				<ogc:PropertyName>sf:decimalProperty</ogc:PropertyName>
				<ogc:Div>
					<ogc:PropertyName>sf:intProperty</ogc:PropertyName>
					<ogc:Literal>2</ogc:Literal>
				</ogc:Div>
			</ogc:PropertyIsGreaterThan>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3039 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsLessThan>
				<ogc:PropertyName>sf:decimalProperty</ogc:PropertyName>
				<ogc:Sub>
					<ogc:PropertyName>sf:intProperty</ogc:PropertyName>
					<ogc:Literal>10</ogc:Literal>
				</ogc:Sub>
			</ogc:PropertyIsLessThan>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3040 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:Function name="ASDF">
					<ogc:PropertyName>sf:intProperty</ogc:PropertyName>
				</ogc:Function>
				<ogc:Literal>1</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3041 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsGreaterThan>
				<ogc:PropertyName>sf:intProperty</ogc:PropertyName>
				<ogc:Mul>
					<ogc:PropertyName>sf:decimalProperty</ogc:PropertyName>
					<ogc:Literal>2</ogc:Literal>
				</ogc:Mul>
			</ogc:PropertyIsGreaterThan>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3042 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>sf:decimalProperty</ogc:PropertyName>
				<ogc:Sub>
					<ogc:PropertyName>sf:intProperty</ogc:PropertyName>
					<ogc:Literal>149.98</ogc:Literal>
				</ogc:Sub>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3043 '
'

$RUN_TEST $VALGRIND 3044 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>*[1]</ogc:PropertyName>
				<ogc:Literal>description-f001</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3045 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3046 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsLike wildCard="*" singleChar="?" escapeChar="\">
				<ogc:PropertyName>gml:name</ogc:PropertyName>
				<ogc:Literal>nam??-f00?</ogc:Literal>
			</ogc:PropertyIsLike>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3047 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:GmlObjectId gml:id="f001"/>
			<ogc:FeatureId fid="f002"/>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3048 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsBetween>
				<ogc:PropertyName>sf:dateProperty</ogc:PropertyName>
				<ogc:LowerBoundary><ogc:Literal>2999-09-01</ogc:Literal></ogc:LowerBoundary>
				<ogc:UpperBoundary><ogc:Literal>2999-11-01</ogc:Literal></ogc:UpperBoundary>
			</ogc:PropertyIsBetween>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3049 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo matchCase="false">
				<ogc:PropertyName>sf:strProperty</ogc:PropertyName>
				<ogc:Literal>mA quANde lIngues COALEsce, li graMMatiCa dEl reSULtAnt.</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3050 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0">
	<wfs:Query xmlns:sf="http://www.opengis.net/ASDF" typeName="sf:Asdf" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3051 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsLike wildCard="*" singleChar="?" escapeChar="\">
				<ogc:PropertyName>gml:name</ogc:PropertyName>
				<ogc:Literal>name-f01?</ogc:Literal>
			</ogc:PropertyIsLike>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3052 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature">
		<ogc:Filter>
			<ogc:BBOX>
				<ogc:PropertyName>sf:intProperty</ogc:PropertyName>
				<gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
					<gml:lowerCorner>47.0 -4.5</gml:lowerCorner>
					<gml:upperCorner>52.0 1.0</gml:upperCorner>
				</gml:Envelope>
			</ogc:BBOX>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3053 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsLike wildCard="*" singleChar="?" escapeChar="\">
				<ogc:PropertyName>sf:dateProperty</ogc:PropertyName>
				<ogc:Literal>20*-10-??</ogc:Literal>
			</ogc:PropertyIsLike>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3054 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS" resultType="hits">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3055 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>//gml:description</ogc:PropertyName>
				<ogc:Literal>description-f008</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3056 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3057 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:EntitéGénérique" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3058 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3059 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:EntitéGénérique" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsNotEqualTo>
				<ogc:PropertyName>sf:boolProperty</ogc:PropertyName>
				<ogc:Literal>0</ogc:Literal>
			</ogc:PropertyIsNotEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3060 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:EntitéGénérique" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:GmlObjectId gml:id="{$gml.id1}"/>
			<ogc:GmlObjectId gml:id="{$gml.id2}"/>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3061 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    xmlns:ogc="http://www.opengis.net/ogc" 
    typeName="sf:AggregateGeoFeature"
    srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
    <ogc:SortBy>
      <ogc:SortProperty>
        <ogc:PropertyName>sf:featureCode</ogc:PropertyName>
        <ogc:SortOrder>ASC</ogc:SortOrder>
      </ogc:SortProperty>
    </ogc:SortBy>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3062 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
      <ogc:PropertyIsNull>
        <ogc:PropertyName>sf:intProperty</ogc:PropertyName>										
      </ogc:PropertyIsNull>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3063 '
<foo:GetFeature xmlns:foo="http://www.opengis.net/wfs" 
  xmlns:gml="http://www.opengis.net/gml" version="1.1.0" service="WFS">
	<foo:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
      typeName="sf:PrimitiveGeoFeature" 
      srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<foo:PropertyName>sf:dateProperty</foo:PropertyName>
	</foo:Query>
</foo:GetFeature>
'

$RUN_TEST $VALGRIND 3064 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsNotEqualTo>
				<ogc:PropertyName>sf:dateProperty</ogc:PropertyName>
				<ogc:Literal>2006-12-12Z</ogc:Literal>
			</ogc:PropertyIsNotEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3065 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:ogc="http://www.opengis.net/ogc" service="WFS" version="1.1.0">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<wfs:PropertyName>sf:asdfProperty</wfs:PropertyName>
	</wfs:Query>
</wfs:GetFeature>
'


# LOGICAL OPERATORS

$RUN_TEST $VALGRIND 3066 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:EntitéGénérique"
    srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Not>
        <ogc:Not>
          <ogc:BBOX>
            <ogc:PropertyName>attribut.Géométrie</ogc:PropertyName>
            <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
              <gml:lowerCorner>55.0 -2.5</gml:lowerCorner>
              <gml:upperCorner>65.0 2.5</gml:upperCorner>
            </gml:Envelope>
          </ogc:BBOX>
        </ogc:Not>
      </ogc:Not>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3067 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
      <ogc:Not>
        <ogc:PropertyIsBetween>
          <ogc:PropertyName>sf:doubleProperty</ogc:PropertyName>
          <ogc:LowerBoundary><ogc:Literal>20.0</ogc:Literal></ogc:LowerBoundary>
          <ogc:UpperBoundary><ogc:Literal>100.0</ogc:Literal></ogc:UpperBoundary>										
        </ogc:PropertyIsBetween>
      </ogc:Not>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3068 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
     xmlns:ogc="http://www.opengis.net/ogc"
    typeName="sf:PrimitiveGeoFeature">
    <ogc:Filter xmlns:gml="http://www.opengis.net/gml">
      <ogc:Or>
        <ogc:PropertyIsNotEqualTo>
          <ogc:PropertyName>sf:intProperty</ogc:PropertyName>
          <ogc:Literal>155</ogc:Literal>
        </ogc:PropertyIsNotEqualTo>
        <ogc:PropertyIsBetween>
          <ogc:PropertyName>sf:decimalProperty</ogc:PropertyName>
          <ogc:LowerBoundary><ogc:Literal>10.00</ogc:Literal></ogc:LowerBoundary>
          <ogc:UpperBoundary><ogc:Literal>20.00</ogc:Literal></ogc:UpperBoundary>										
        </ogc:PropertyIsBetween>
      </ogc:Or>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3069 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:AggregateGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
      <ogc:And>
        <ogc:PropertyIsGreaterThanOrEqualTo>
          <ogc:PropertyName>sf:doubleProperty</ogc:PropertyName>
          <ogc:Literal>24510</ogc:Literal>
        </ogc:PropertyIsGreaterThanOrEqualTo>
        <ogc:PropertyIsEqualTo matchCase="false">
          <ogc:PropertyName>sf:featureCode</ogc:PropertyName>
          <ogc:Literal>ak020</ogc:Literal>
        </ogc:PropertyIsEqualTo>
      </ogc:And>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3070 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:EntitéGénérique"
    srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" 
      xmlns:gml="http://www.opengis.net/gml">
      <ogc:Not>
        <ogc:BBOX>
          <ogc:PropertyName>attribut.Géométrie</ogc:PropertyName>
          <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:lowerCorner>34.0 16.0</gml:lowerCorner>
            <gml:upperCorner>40.0 19.0</gml:upperCorner>
          </gml:Envelope>
        </ogc:BBOX>
      </ogc:Not>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3071 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:PrimitiveGeoFeature"
    srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:And>
        <ogc:BBOX>
          <ogc:PropertyName>sf:pointProperty</ogc:PropertyName>
          <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11:4326">
            <gml:lowerCorner>36.0 -1.0</gml:lowerCorner>
            <gml:upperCorner>42.0 4.0</gml:upperCorner>
          </gml:Envelope>
        </ogc:BBOX>
        <ogc:PropertyIsGreaterThan>
          <ogc:PropertyName>sf:dateProperty</ogc:PropertyName>
          <ogc:Literal>2006-10-01Z</ogc:Literal>
        </ogc:PropertyIsGreaterThan>
      </ogc:And>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3072 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:AggregateGeoFeature"
    srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:And>
        <ogc:Not>
          <ogc:BBOX>
            <ogc:PropertyName />
            <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
              <gml:lowerCorner>40.0 -5.0</gml:lowerCorner>
              <gml:upperCorner>50.0 -1.0</gml:upperCorner>
            </gml:Envelope>
          </ogc:BBOX>
        </ogc:Not>
        <ogc:PropertyIsGreaterThan>
          <ogc:PropertyName>sf:doubleProperty</ogc:PropertyName>
          <ogc:Literal>20.0</ogc:Literal>
        </ogc:PropertyIsGreaterThan>
      </ogc:And>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3073 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    xmlns:ogc="http://www.opengis.net/ogc" 
    typeName="sf:EntitéGénérique"
    srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
    <ogc:Filter xmlns:gml="http://www.opengis.net/gml">
      <ogc:Or>
        <ogc:PropertyIsEqualTo>
          <ogc:PropertyName>sf:str4Property</ogc:PropertyName>
          <ogc:Literal>abc3</ogc:Literal>
        </ogc:PropertyIsEqualTo>
        <ogc:BBOX>
          <ogc:PropertyName>sf:attribut.Géométrie</ogc:PropertyName>
          <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:lowerCorner>34.0 15.0</gml:lowerCorner>
            <gml:upperCorner>40.0 19.0</gml:upperCorner>
          </gml:Envelope>
        </ogc:BBOX>
      </ogc:Or>
    </ogc:Filter>
    <ogc:SortBy>
      <ogc:SortProperty>
        <ogc:PropertyName>sf:str4Property</ogc:PropertyName>
        <ogc:SortOrder>ASC</ogc:SortOrder>
      </ogc:SortProperty>
    </ogc:SortBy>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3074 '
'

$RUN_TEST $VALGRIND 3075 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature">
		<ogc:Filter>
			<ogc:BBOX>
				<ogc:PropertyName>sf:pointProperty</ogc:PropertyName>
				<gml:Envelope>
					<gml:lowerCorner>37.0 -2.5</gml:lowerCorner>
					<gml:upperCorner>42.0 2.5</gml:upperCorner>
				</gml:Envelope>
			</ogc:BBOX>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3076 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature">
		<ogc:Filter>
			<ogc:BBOX>
				<ogc:PropertyName>sf:pointProperty</ogc:PropertyName>
				<gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
					<gml:lowerCorner>50 -15</gml:lowerCorner>
					<gml:upperCorner>72 5</gml:upperCorner>
				</gml:Envelope>
			</ogc:BBOX>
		</ogc:Filter>
	</wfs:Query>
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:EntitéGénérique">
		<ogc:Filter>
			<ogc:BBOX>
				<ogc:PropertyName>sf:attribut.Géométrie</ogc:PropertyName>
				<gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
					<gml:lowerCorner>50 -15</gml:lowerCorner>
					<gml:upperCorner>72 5</gml:upperCorner>
				</gml:Envelope>
			</ogc:BBOX>
		</ogc:Filter>
	</wfs:Query>
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature">
		<ogc:Filter>
			<ogc:BBOX>
				<ogc:PropertyName>sf:multiCurveProperty</ogc:PropertyName>
				<gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
					<gml:lowerCorner>50 -15</gml:lowerCorner>
					<gml:upperCorner>72 5</gml:upperCorner>
				</gml:Envelope>
			</ogc:BBOX>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3077 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<wfs:PropertyName>sf:dateProperty</wfs:PropertyName>
		<wfs:PropertyName>sf:dateTimeProperty</wfs:PropertyName>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3078 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:EntitéGénérique" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>gml:description</ogc:PropertyName>
				<ogc:Literal>description-f004</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3079 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsBetween>
				<ogc:PropertyName>sf:doubleProperty</ogc:PropertyName>
				<ogc:LowerBoundary><ogc:Literal>20.1</ogc:Literal></ogc:LowerBoundary>
				<ogc:UpperBoundary><ogc:Literal>24509.5</ogc:Literal></ogc:UpperBoundary>
			</ogc:PropertyIsBetween>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3080 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:Asdf" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>
'


# SPATIAL OPERATORS

$RUN_TEST $VALGRIND 3081 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:PrimitiveGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Contains>
        <ogc:PropertyName>sf:curveProperty</ogc:PropertyName>
        <gml:LineString srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:posList>46.074 9.799 46.652 10.466</gml:posList>
        </gml:LineString>        
      </ogc:Contains>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3082 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:AggregateGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Disjoint>
        <ogc:PropertyName>sf:multiCurveProperty</ogc:PropertyName>
        <gml:Curve srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:segments>
            <gml:Circle interpolation="circularArc3Points">
              <gml:posList>57.5 19.0 57.0 20.0 57.5 21.0</gml:posList>
            </gml:Circle>
          </gml:segments>
        </gml:Curve>
        </ogc:Disjoint>
      </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3083 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:EntitéGénérique">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Overlaps>
        <ogc:PropertyName>sf:attribut.Géométrie</ogc:PropertyName>
        <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:lowerCorner>56.05 -2.00</gml:lowerCorner>
          <gml:upperCorner>62.11 2.02</gml:upperCorner>
        </gml:Envelope>
      </ogc:Overlaps>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3084 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:AggregateGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Crosses>
          <ogc:PropertyName>sf:multiSurfaceProperty</ogc:PropertyName>
			<gml:LineString srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
			  <gml:posList>53 22 54 21 54 20 54 19 54 18 54 17</gml:posList>
			</gml:LineString>
      </ogc:Crosses>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3085 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature">
		<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
			<ogc:Touches>
				<ogc:PropertyName>sf:multiCurveProperty</ogc:PropertyName>
				<gml:Point srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
					<gml:pos>55.174 -5.899</gml:pos>
				</gml:Point>
			</ogc:Touches>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3086 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Contains>
        <ogc:PropertyName>sf:multiSurfaceProperty</ogc:PropertyName>
        <gml:Polygon srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:exterior>
            <gml:LinearRing>
              <gml:posList>35.1 -8.0 35.1 -8.4 35.2 -8.4 35.2 -8.0 35.1 -8.0</gml:posList>
            </gml:LinearRing>
          </gml:exterior>
        </gml:Polygon>										
      </ogc:Contains>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3087 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:AggregateGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Touches>
          <ogc:PropertyName>sf:multiSurfaceProperty</ogc:PropertyName>
			<gml:LineString srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
			  <gml:posList>54 19 54 18 54 17</gml:posList>
			</gml:LineString>
      </ogc:Touches>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3088 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:EntitéGénérique">
		<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
			<ogc:Contains>
				<ogc:PropertyName>sf:attribut.Géométrie</ogc:PropertyName>
				<gml:Point srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
					<gml:pos>63.123 5.321</gml:pos>
				</gml:Point>
			</ogc:Contains>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3089 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:EntitéGénérique">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Intersects>
        <ogc:PropertyName>sf:attribut.Géométrie</ogc:PropertyName>
        <gml:MultiPoint srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:pointMember>
            <gml:Point><gml:pos>38.83 16.22</gml:pos></gml:Point>
          </gml:pointMember>
          <gml:pointMember>
            <gml:Point><gml:pos>62.07 2.48</gml:pos></gml:Point>
          </gml:pointMember>
        </gml:MultiPoint>										
      </ogc:Intersects>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3090 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:AggregateGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Disjoint>
          <ogc:PropertyName>sf:multiSurfaceProperty</ogc:PropertyName>
          <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:lowerCorner>48.0 18.0</gml:lowerCorner>
            <gml:upperCorner>52.0 21.0</gml:upperCorner>
          </gml:Envelope>
      </ogc:Disjoint>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3091 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Within>
        <ogc:PropertyName>sf:pointProperty</ogc:PropertyName>
        <gml:Polygon srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:exterior>
            <gml:LinearRing>
              <gml:posList>38.0 0.0 38.0 6.0 43.0 0.0 38.0 0.0</gml:posList>
            </gml:LinearRing>
          </gml:exterior>
        </gml:Polygon>										
      </ogc:Within>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3092 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:AggregateGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Intersects>
        <ogc:PropertyName>sf:multiSurfaceProperty</ogc:PropertyName>
        <gml:LinearRing srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:posList>57.0 7.5 57.0 8.5 58.0 8.5 58.0 7.5 57.0 7.5</gml:posList>
        </gml:LinearRing>										
      </ogc:Intersects>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3093 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:EntitéGénérique">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Equals>
        <ogc:PropertyName>sf:attribut.Géométrie</ogc:PropertyName>
        <gml:Polygon srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:exterior>
            <gml:LinearRing>
              <gml:posList>60.5 0 64 0 64 6.25 60.5 6.25 60.5 0</gml:posList>
            </gml:LinearRing>
          </gml:exterior>
          <gml:interior>
            <gml:LinearRing>
              <gml:posList>61.5 2 62.5 2 62 4 61.5 2</gml:posList>
            </gml:LinearRing>
          </gml:interior>
        </gml:Polygon>
      </ogc:Equals>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3094 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:PrimitiveGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Touches>
          <ogc:PropertyName>sf:surfaceProperty</ogc:PropertyName>
          <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:lowerCorner>0.1 -1.0</gml:lowerCorner>
            <gml:upperCorner>0.2 -0.9</gml:upperCorner>
          </gml:Envelope>									
      </ogc:Touches>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3095 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:EntitéGénérique">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:BBOX>
          <ogc:PropertyName />
          <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:lowerCorner>34 14</gml:lowerCorner>
            <gml:upperCorner>41 23</gml:upperCorner>
          </gml:Envelope>
      </ogc:BBOX>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3096 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:PrimitiveGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Within>
        <ogc:PropertyName>sf:curveProperty</ogc:PropertyName>
        <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:lowerCorner>45.050 8.800</gml:lowerCorner>
          <gml:upperCorner>47.114 11.021</gml:upperCorner>
        </gml:Envelope>
      </ogc:Within>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3097 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Overlaps>
        <ogc:PropertyName>sf:surfaceProperty</ogc:PropertyName>
        <gml:LineString srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:posList>44.80 30.75 46.50 30.75 48.00 31.25</gml:posList>
        </gml:LineString>
      </ogc:Overlaps>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3098 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Equals>
        <ogc:PropertyName>sf:pointProperty</ogc:PropertyName>
        <gml:Point srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:pos>59.41276 0.22601</gml:pos>
        </gml:Point>
      </ogc:Equals>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3099 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:AggregateGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Intersects>
        <ogc:PropertyName>sf:curveProperty</ogc:PropertyName>
        <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:lowerCorner>56.0 -8.0</gml:lowerCorner>
            <gml:upperCorner>60.0 -2.0</gml:upperCorner>
        </gml:Envelope>
      </ogc:Intersects>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3100 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature">
		<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
			<ogc:Crosses>
				<ogc:PropertyName>sf:curveProperty</ogc:PropertyName>
				<gml:LineString srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
					<gml:posList>47.1 9.8 46.1 11.0</gml:posList>
				</gml:LineString>
			</ogc:Crosses>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3101 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:PrimitiveGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Crosses>
          <ogc:PropertyName>sf:surfaceProperty</ogc:PropertyName>
			<gml:LineString srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
			  <gml:posList>0 0 1 1 2 2</gml:posList>
			</gml:LineString>									
      </ogc:Crosses>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3102 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Overlaps>
        <ogc:PropertyName>sf:curveProperty</ogc:PropertyName>
        <gml:LineString srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:posList>46.652 10.466 47.114 11.021 46.114 12.114 45.725 12.523</gml:posList>
        </gml:LineString>
      </ogc:Overlaps>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3103 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:PrimitiveGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Intersects>
        <ogc:PropertyName>sf:pointProperty</ogc:PropertyName>
        <gml:Polygon srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:exterior>
            <gml:LinearRing>
              <gml:posList>34.0 -12.0 34.0 4.0 42.0 4.0 42.0 -12.0 34.0 -12.0</gml:posList>
            </gml:LinearRing>
          </gml:exterior>
        </gml:Polygon>										
      </ogc:Intersects>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3104 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:EntitéGénérique">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Within>
        <ogc:PropertyName />
        <gml:Polygon srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:exterior>
            <gml:LinearRing>
              <gml:posList>55.1 -8.0 55.1 -5.4 60.0 -5.4 60.0 -8.0 55.1 -8.0</gml:posList>
            </gml:LinearRing>
          </gml:exterior>
        </gml:Polygon>										
      </ogc:Within>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3105 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Equals>
        <ogc:PropertyName>sf:multiPointProperty</ogc:PropertyName>
        <gml:MultiPoint srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:pointMember>
            <gml:Point><gml:pos>70.83 29.86</gml:pos></gml:Point>
          </gml:pointMember>
          <gml:pointMember>
            <gml:Point><gml:pos>68.87 31.08</gml:pos></gml:Point>
          </gml:pointMember>
          <gml:pointMember>
            <gml:Point><gml:pos>71.96 32.19</gml:pos></gml:Point>
          </gml:pointMember>
        </gml:MultiPoint>
      </ogc:Equals>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3106 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    typeName="sf:PrimitiveGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Disjoint>
          <ogc:PropertyName>sf:surfaceProperty</ogc:PropertyName>
          <gml:LineString srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
            <gml:posList>45.017 30.422 45.208 30.603 45.757 30.812 45.957 30.926</gml:posList>
          </gml:LineString>										
      </ogc:Disjoint>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3107 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
      <ogc:Overlaps>
        <ogc:PropertyName>sf:multiSurfaceProperty</ogc:PropertyName>
        <gml:MultiSurface srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
          <gml:surfaceMember>
			<gml:Polygon>
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>48.0 18.0 48.0 23.0 54.0 23.0 54.0 18.0 48.0 18.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
			</gml:Polygon>
		  </gml:surfaceMember>
		  <gml:surfaceMember>
            <gml:Polygon>
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>59.0 4.0 55.0 8.0 59.0 12.0 59.0 4.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </ogc:Overlaps>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3108 '
'

$RUN_TEST $VALGRIND 3109 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature">
		<ogc:Filter>
			<ogc:BBOX>
				<ogc:PropertyName>sf:pointProperty</ogc:PropertyName>
				<gml:Envelope srsName="urn:x-ogc:def:crs:ASDF:9.99:9999">
					<gml:lowerCorner>47.0 -4.5</gml:lowerCorner>
					<gml:upperCorner>52.0 1.0</gml:upperCorner>
				</gml:Envelope>
			</ogc:BBOX>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3110 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsGreaterThan>
				<ogc:PropertyName>sf:decimalProperty</ogc:PropertyName>
				<ogc:Literal>12.5</ogc:Literal>
			</ogc:PropertyIsGreaterThan>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3111 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml"  xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<wfs:PropertyName>sf:measurand</wfs:PropertyName>
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>gml:name</ogc:PropertyName>
				<ogc:Literal>name-f001</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3112 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
	<wfs:Smuery xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3113 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>sf:dateProperty</ogc:PropertyName>
				<ogc:Literal>2999-12-12</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3114 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature">
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
      <ogc:PropertyIsNull>
        <ogc:PropertyName>sf:multiCurveProperty</ogc:PropertyName>
      </ogc:PropertyIsNull>
    </ogc:Filter>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3115 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsBetween>
				<ogc:PropertyName>sf:decimalProperty</ogc:PropertyName>
				<ogc:LowerBoundary><ogc:Literal>10</ogc:Literal></ogc:LowerBoundary>
				<ogc:UpperBoundary><ogc:Literal>20</ogc:Literal></ogc:UpperBoundary>
			</ogc:PropertyIsBetween>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3116 '
<foo:GetFeature xmlns:foo="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
	<foo:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</foo:GetFeature>'

$RUN_TEST $VALGRIND 3117 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0">
	<wfs:Query xmlns:ogc="http://www.opengis.net/ogc" xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName xmlns:gml="http://www.opengis.net/gml">gml:name</ogc:PropertyName>
				<ogc:Literal>name-f002</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3118 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>gml:name</ogc:PropertyName>
				<ogc:Literal>
					<wfs:Native vendorId="ASDF" safeToIgnore="true"/>
				</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3119 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:GmlObjectId gml:id="{$gml.id}"/>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3120 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsGreaterThanOrEqualTo>
				<ogc:PropertyName>sf:doubleProperty</ogc:PropertyName>
				<ogc:Literal>2012.78</ogc:Literal>
			</ogc:PropertyIsGreaterThanOrEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3121 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsNotEqualTo>
				<ogc:PropertyName>sf:intProperty</ogc:PropertyName>
				<ogc:Literal>300</ogc:Literal>
			</ogc:PropertyIsNotEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3122 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsNotEqualTo matchCase="false">
				<ogc:PropertyName>gml:description</ogc:PropertyName>
				<ogc:Literal>deSCRIption-F003</ogc:Literal>
			</ogc:PropertyIsNotEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3123 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3124 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3125 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature">
		<ogc:Filter>
			<ogc:BBOX>
				<ogc:PropertyName>sf:pointProperty</ogc:PropertyName>
				<gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
					<gml:lowerCorner>57.0 -4.5</gml:lowerCorner>
					<gml:upperCorner>62.0 1.0</gml:upperCorner>
				</gml:Envelope>
			</ogc:BBOX>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3126 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:9.99.9:99999"/>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3127 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsNotEqualTo>
				<ogc:PropertyName>gml:description</ogc:PropertyName>
				<ogc:Literal>description-f003</ogc:Literal>
			</ogc:PropertyIsNotEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3128 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:BBOX>
				<ogc:PropertyName>sf:pointProperty</ogc:PropertyName>
				<gml:Envelope>
					<gml:lowerCorner>37.0 -2.5</gml:lowerCorner>
					<gml:upperCorner>42.0 2.5</gml:upperCorner>
				</gml:Envelope>
			</ogc:BBOX>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3129 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsLessThan>
				<ogc:PropertyName>sf:decimalProperty</ogc:PropertyName>
				<ogc:Literal>15</ogc:Literal>
			</ogc:PropertyIsLessThan>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3130 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsLessThanOrEqualTo>
				<ogc:PropertyName>sf:intProperty</ogc:PropertyName>
				<ogc:Literal>180</ogc:Literal>
			</ogc:PropertyIsLessThanOrEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3131 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0">
	<sf:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3132 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:EntitéGénérique" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName>sf:boolProperty</ogc:PropertyName>
				<ogc:Literal>1</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3133 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsLessThanOrEqualTo>
				<ogc:PropertyName>sf:dateTimeProperty</ogc:PropertyName>
				<ogc:Literal>2006-06-28T19:08:00+02:00</ogc:Literal>
			</ogc:PropertyIsLessThanOrEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3134 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsLessThan>
				<ogc:PropertyName>sf:intProperty</ogc:PropertyName>
				<ogc:Literal>100</ogc:Literal>
			</ogc:PropertyIsLessThan>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3135 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="FOO">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3136 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
  <wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" 
    xmlns:ogc="http://www.opengis.net/ogc" 
    typeName="sf:PrimitiveGeoFeature"
    srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
    <ogc:SortBy>
      <ogc:SortProperty>
        <ogc:PropertyName>sf:intProperty</ogc:PropertyName>
        <ogc:SortOrder>DESC</ogc:SortOrder>
      </ogc:SortProperty>
    </ogc:SortBy>
  </wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3137 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3138 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3139 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" version="" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3140 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs"  xmlns:ogc="http://www.opengis.net/ogc" service="WFS" version="1.1.0">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsEqualTo>
				<ogc:PropertyName xmlns:gml="http://www.opengis.net/gml">gml:name</ogc:PropertyName>
				<ogc:Literal>name-f003</ogc:Literal>
			</ogc:PropertyIsEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3141 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsGreaterThanOrEqualTo>
				<ogc:PropertyName>sf:decimalProperty</ogc:PropertyName>
				<ogc:Literal>12.5</ogc:Literal>
			</ogc:PropertyIsGreaterThanOrEqualTo>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3142 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3143 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:AggregateGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
		<ogc:Filter>
			<ogc:PropertyIsLessThan>
				<ogc:PropertyName>sf:doubleProperty</ogc:PropertyName>
				<ogc:Literal>2200.11</ogc:Literal>
			</ogc:PropertyIsLessThan>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>
'

$RUN_TEST $VALGRIND 3144 '
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.1.0" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature">
		<ogc:Filter>
			<ogc:BBOX>
				<ogc:PropertyName>sf:pointProperty</ogc:PropertyName>
				<gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326">
					<gml:lowerCorner>39.63245 1.90342</gml:lowerCorner>
					<gml:upperCorner>39.73245 2.00342</gml:upperCorner>
				</gml:Envelope>
			</ogc:BBOX>
		</ogc:Filter>
	</wfs:Query>
</wfs:GetFeature>'

$RUN_TEST $VALGRIND 3145 '
<wfs:GetFeature version="11-02-2006" xmlns:wfs="http://www.opengis.net/wfs" service="WFS">
	<wfs:Query xmlns:sf="http://cite.opengeospatial.org/gmlsf" typeName="sf:PrimitiveGeoFeature" srsName="urn:x-ogc:def:crs:EPSG:6.11.2:4326"/>
</wfs:GetFeature>
'

