<HTML>

<?php 

// phpinfo_mapscript.phtml
//
// Use this script to test that the PHP/MapScript module has been
// properly installed and can be loaded by PHP.
//
// Accessing this page through the web server where the module
// has been installed should report the MapScript module version
// number in the list of modules in the phpinfo() output.
//

if (PHP_OS == "WINNT" || PHP_OS == "WIN32")
{
  dl("php3_mapscript.dll");
}
else
{
  dl("php_mapscript.so");
}

  phpinfo();

?>

</HTML>
